export const API_BASE = (() => {
  const isFile = window.location.protocol === 'file:';
  const staticDevPorts = new Set(['5173', '5500', '8000', '8080']);
  const isStaticDevServer = staticDevPorts.has(window.location.port);
  if (!isFile && !isStaticDevServer) return `${window.location.origin}/api`;
  return 'http://localhost:3000/api';
})();

export const state = {
  locations:   [],       // All zone objects from /api/locations
  lastResult:  null,     // Most recent /api/valuate response
  pinnedZones: [],       // Zones pinned for comparison (max 3)
};

export const charts = {
  comparisonChart:  null,
  emiChart:         null,
  sensitivityChart: null,
  radarChart:       null,
};

// All 28 Indian states + Delhi (UT) — alphabetically sorted
export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan',
  'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
  'Uttarakhand', 'West Bengal',
];

// City → State mapping (extend as new cities are added to data.json)
export const CITY_STATE_MAP = {
  "Visakhapatnam": "Andhra Pradesh",
  "Vijayawada": "Andhra Pradesh",
  "Guntur": "Andhra Pradesh",
  "Nellore": "Andhra Pradesh",
  "Tirupati": "Andhra Pradesh",
  "Itanagar": "Arunachal Pradesh",
  "Tawang": "Arunachal Pradesh",
  "Naharlagun": "Arunachal Pradesh",
  "Guwahati": "Assam",
  "Silchar": "Assam",
  "Dibrugarh": "Assam",
  "Jorhat": "Assam",
  "Patna": "Bihar",
  "Gaya": "Bihar",
  "Bhagalpur": "Bihar",
  "Muzaffarpur": "Bihar",
  "Raipur": "Chhattisgarh",
  "Bhilai": "Chhattisgarh",
  "Bilaspur": "Chhattisgarh",
  "Korba": "Chhattisgarh",
  "Central Delhi": "Delhi",
  "South Delhi": "Delhi",
  "Dwarka": "Delhi",
  "Rohini": "Delhi",
  "East Delhi": "Delhi",
  "Panaji": "Goa",
  "Margao": "Goa",
  "Vasco da Gama": "Goa",
  "Mapusa": "Goa",
  "Ahmedabad": "Gujarat",
  "Surat": "Gujarat",
  "Vadodara": "Gujarat",
  "Rajkot": "Gujarat",
  "Gandhinagar": "Gujarat",
  "Gurugram": "Haryana",
  "Faridabad": "Haryana",
  "Panchkula": "Haryana",
  "Panipat": "Haryana",
  "Rohtak": "Haryana",
  "Hisar": "Haryana",
  "Karnal": "Haryana",
  "Shimla": "Himachal Pradesh",
  "Dharamshala": "Himachal Pradesh",
  "Mandi": "Himachal Pradesh",
  "Solan": "Himachal Pradesh",
  "Ranchi": "Jharkhand",
  "Jamshedpur": "Jharkhand",
  "Dhanbad": "Jharkhand",
  "Bokaro": "Jharkhand",
  "Bengaluru": "Karnataka",
  "Mysuru": "Karnataka",
  "Mangaluru": "Karnataka",
  "Hubballi": "Karnataka",
  "Belagavi": "Karnataka",
  "Thiruvananthapuram": "Kerala",
  "Kochi": "Kerala",
  "Kozhikode": "Kerala",
  "Thrissur": "Kerala",
  "Kollam": "Kerala",
  "Indore": "Madhya Pradesh",
  "Bhopal": "Madhya Pradesh",
  "Jabalpur": "Madhya Pradesh",
  "Gwalior": "Madhya Pradesh",
  "Ujjain": "Madhya Pradesh",
  "Mumbai": "Maharashtra",
  "Pune": "Maharashtra",
  "Nagpur": "Maharashtra",
  "Nashik": "Maharashtra",
  "Aurangabad": "Maharashtra",
  "Thane": "Maharashtra",
  "Imphal": "Manipur",
  "Churachandpur": "Manipur",
  "Thoubal": "Manipur",
  "Shillong": "Meghalaya",
  "Tura": "Meghalaya",
  "Jowai": "Meghalaya",
  "Aizawl": "Mizoram",
  "Lunglei": "Mizoram",
  "Champhai": "Mizoram",
  "Kohima": "Nagaland",
  "Dimapur": "Nagaland",
  "Mokokchung": "Nagaland",
  "Bhubaneswar": "Odisha",
  "Cuttack": "Odisha",
  "Rourkela": "Odisha",
  "Puri": "Odisha",
  "Berhampur": "Odisha",
  "Ludhiana": "Punjab",
  "Amritsar": "Punjab",
  "Jalandhar": "Punjab",
  "Patiala": "Punjab",
  "Bathinda": "Punjab",
  "Jaipur": "Rajasthan",
  "Jodhpur": "Rajasthan",
  "Udaipur": "Rajasthan",
  "Kota": "Rajasthan",
  "Bikaner": "Rajasthan",
  "Gangtok": "Sikkim",
  "Namchi": "Sikkim",
  "Geyzing": "Sikkim",
  "Chennai": "Tamil Nadu",
  "Coimbatore": "Tamil Nadu",
  "Madurai": "Tamil Nadu",
  "Tiruchirappalli": "Tamil Nadu",
  "Salem": "Tamil Nadu",
  "Hyderabad": "Telangana",
  "Warangal": "Telangana",
  "Nizamabad": "Telangana",
  "Karimnagar": "Telangana",
  "Agartala": "Tripura",
  "Dharmanagar": "Tripura",
  "Udaipur (TR)": "Tripura",
  "Lucknow": "Uttar Pradesh",
  "Kanpur": "Uttar Pradesh",
  "Noida": "Uttar Pradesh",
  "Ghaziabad": "Uttar Pradesh",
  "Varanasi": "Uttar Pradesh",
  "Agra": "Uttar Pradesh",
  "Prayagraj": "Uttar Pradesh",
  "Dehradun": "Uttarakhand",
  "Haridwar": "Uttarakhand",
  "Roorkee": "Uttarakhand",
  "Haldwani": "Uttarakhand",
  "Kolkata": "West Bengal",
  "Howrah": "West Bengal",
  "Asansol": "West Bengal",
  "Siliguri": "West Bengal",
  "Durgapur": "West Bengal"
};
